log:
  # Options include: trace debug info warn error critical off
  level: info

mongo:
  # MongoDB address
  uri: "mongodb://username:password@host:port/database"
  # map
  map:
    db: "v2"
    col: "map_beijing5ring_0424"
  # Communication Topology
  comm_topo:
    db: "v2"
    col: "comm_beijing5ring_0625"
  # Communication Demand
  comm_demand:
    db: "yuqiaohong"
    col: "comm_baoyu_new"
  # # Communication Ray Tracing
  # ray_tracing_loss:
  #   db: "yuqiaohong"
  #   col: "ray_tracing_loss_guomao_new"

control:
  step:
    # Simulator Start Step
    start: 25200 # 6:00 AM
    # Total Simulation Steps, End Step is Start Step + Total Steps
    total: 1800 # 6 Hours
    # Time Interval per Step
    interval: 1.0
  thread:
    #  Number of Threads Used in Multi-Threading, 0 Represents Using All Threads
    worker: 0
    # Task Block Size Processed by Each Thread (Tuning Parameter)
    block_size: 250
  # Simulator Vehicle Output Range (Latitude and Longitude Coordinates)
  microscopic_range: # Beijing Guomao
    min_longitude: 116.45466845743775
    min_latitude: 39.90635904559525
    max_longitude: 116.4727503404667
    max_latitude: 39.92235997926467
  macroscopic_range: # Beijing Fifth Ring Road
    min_longitude: 116.2017
    min_latitude: 39.7563
    max_longitude: 116.5443
    max_latitude: 40.0231
  enable_controlled: true
  enable_optimize: false
  optimize_interval: 8
  display_guomao: true
  coverage_range: 1000
  handover_interval: 1
  channel_type: 1
  antenna_type: 1

output:
  target:
    # sql: "postgres://sim:WZ8RDE7woHwBhRKp1UIP55Yjio5SHr7y@pg-visual.db.internal.tsingroc.tech/simulation"
    sql: "postgres://postgres:U59WQA3pwKsaDDt6fVtJetMpnvBfSgsS@rl1.tsingroc.tech/simulation?sslmode=disable"
  switch:
    person: false
    base_station: false
    aoi: false
    heatmap: false
    stats: true
